Repository Chillkongju/Backend, pull requests merged in 2025-07, with the labels that each got.

#4 [chore/#3]: 개발 환경 세팅
  .env
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/backend/baba/BabaApplication.java
  src/main/resources/application.yml
  src/test/java/backend/baba/BabaApplicationTests.java
Labels: Feat

#6 [chore/#5]: 환경변수 파일 삭제
  .env
Labels: Chore

#8 [feat/#7]: 기본 도메인 엔티티 정의 및 서비스 레이어 패키지 구성
  src/main/java/backend/baba/comment/controller/CommentController.java
  src/main/java/backend/baba/comment/domain/Comment.java
  src/main/java/backend/baba/comment/repository/CommentRepository.java
  src/main/java/backend/baba/comment/service/CommentService.java
  src/main/java/backend/baba/diary/controller/DiaryController.java
  src/main/java/backend/baba/diary/domain/Diary.java
  src/main/java/backend/baba/diary/repository/DiaryRepository.java
  src/main/java/backend/baba/diary/service/DiaryService.java
  src/main/java/backend/baba/friend/controller/FriendController.java
  src/main/java/backend/baba/friend/domain/Friend.java
  src/main/java/backend/baba/friend/respository/FriendRepository.java
  src/main/java/backend/baba/friend/service/FriendService.java
  src/main/java/backend/baba/love/controller/LoveController.java
  src/main/java/backend/baba/love/domain/Love.java
  src/main/java/backend/baba/love/repository/LoveRepository.java
  src/main/java/backend/baba/love/service/LoveService.java
  src/main/java/backend/baba/member/controller/MemberController.java
  src/main/java/backend/baba/member/domain/Member.java
  src/main/java/backend/baba/member/repository/MemberRepository.java
  src/main/java/backend/baba/member/service/MemberService.java
  src/main/java/backend/baba/recommendation/controller/RecommendationController.java
  src/main/java/backend/baba/recommendation/domain/Recommendation.java
  src/main/java/backend/baba/recommendation/repository/RecommendationRepository.java
  src/main/java/backend/baba/recommendation/service/RecommendationService.java
Labels: Feat

#10 [chore/#9]: Swagger 연동
  build.gradle
  src/main/java/backend/baba/global/config/SecurityConfig.java
  src/main/java/backend/baba/global/config/SwaggerConfig.java
Labels: Chore, Feat

#16 [feat/#11]: 문화생활 기록 작성 기능 구현
  src/main/java/backend/baba/diary/controller/DiaryController.java
  src/main/java/backend/baba/diary/domain/Category.java
  src/main/java/backend/baba/diary/domain/Diary.java
  src/main/java/backend/baba/diary/dto/request/DiaryCreateRequest.java
  src/main/java/backend/baba/diary/dto/response/DiaryResponse.java
  src/main/java/backend/baba/diary/repository/DiaryRepository.java
  src/main/java/backend/baba/diary/service/DiaryService.java
  src/main/java/backend/baba/global/entity/BaseTimeEntity.java
Labels: Feat

#21 [feat/#19]: 문화생활기록 단일 조회 기능 구현
  src/main/java/backend/baba/diary/controller/DiaryController.java
  src/main/java/backend/baba/diary/repository/DiaryRepository.java
  src/main/java/backend/baba/diary/service/DiaryService.java
Labels: Feat

#23 [chore/#22]: 환경변수 설정
  src/main/resources/application.yml
Labels: Chore

#27 [feat/#24]: 문화생활 기록 삭제 기능 구현
  src/main/java/backend/baba/diary/controller/DiaryController.java
  src/main/java/backend/baba/diary/service/DiaryService.java
Labels: Feat

#28 feat: 팔로우 기능 구현
  src/main/java/backend/baba/friend/controller/FriendController.java
  src/main/java/backend/baba/friend/domain/Friend.java
  src/main/java/backend/baba/friend/repository/FriendRepository.java
  src/main/java/backend/baba/friend/respository/FriendRepository.java
  src/main/java/backend/baba/friend/service/FriendService.java
Labels: Feat

#33 feat: 언팔로우 기능 추가
  src/main/java/backend/baba/friend/controller/FriendController.java
  src/main/java/backend/baba/friend/service/FriendService.java
Labels: Feat

#37 feat: 전체 피드 조회 기능 구현
  src/main/java/backend/baba/diary/repository/DiaryRepository.java
  src/main/java/backend/baba/feed/controller/FeedController.java
  src/main/java/backend/baba/feed/service/FeedService.java
  src/main/java/backend/baba/friend/service/FriendService.java
Labels: Feat

#45 [Feat/#40] Gpt API 연동 및 문화생활기록 기반 일일 작품 추천 API 구현
  src/main/java/backend/baba/global/config/GptConfig.java
  src/main/java/backend/baba/gpt/dto/request/GptRequest.java
  src/main/java/backend/baba/gpt/dto/response/GptResponse.java
  src/main/java/backend/baba/gpt/service/GptService.java
  src/main/java/backend/baba/recommendation/controller/RecommendationController.java
  src/main/java/backend/baba/recommendation/domain/Recommendation.java
  src/main/java/backend/baba/recommendation/dto/RecommendationResponse.java
  src/main/java/backend/baba/recommendation/repository/RecommendationRepository.java
  src/main/java/backend/baba/recommendation/service/RecommendationService.java
  src/main/resources/application.yml
Labels: Feat

#49 [feat/#48]: 월별 문화생활 추천 기능 구현
  src/main/java/backend/baba/diary/domain/Category.java
  src/main/java/backend/baba/diary/repository/DiaryRepository.java
  src/main/java/backend/baba/recommendation/controller/RecommendationController.java
  src/main/java/backend/baba/recommendation/domain/Recommendation.java
  src/main/java/backend/baba/recommendation/dto/CategoryRecommendationResponse.java
  src/main/java/backend/baba/recommendation/repository/RecommendationRepository.java
  src/main/java/backend/baba/recommendation/service/RecommendationService.java
Labels: Feat

#53 [feat/#52]: 월별 문화생활 추천 리스트 전체 조회 기능 구현
  src/main/java/backend/baba/recommendation/controller/RecommendationController.java
  src/main/java/backend/baba/recommendation/repository/RecommendationRepository.java
  src/main/java/backend/baba/recommendation/service/RecommendationService.java
Labels: Feat

#62 [fix/#61]: 문화생활기록 삭제 기능 오류 수정
  src/main/java/backend/baba/diary/controller/DiaryController.java
  src/main/java/backend/baba/diary/repository/DiaryRepository.java
  src/main/java/backend/baba/diary/service/DiaryService.java
Labels: Fix
